name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Adam-rk, adam-nlem
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_trim: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/wakatime.svg
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          
